In [51]:
#Formation energy

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [111]:
data=pd.read_csv("formation_data.csv")

In [112]:
data.head()

,jid,spg_number,spg_symbol,formula,formation_energy_peratom,func,optb88vdw_bandgap
0,JVASP-90856,129,P4/nmm,TiCuSiAs,-0.42762,OptB88vdW,0.000
1,JVASP-86097,221,Pm-3m,DyB6,-0.41596,OptB88vdW,0.000
2,JVASP-64906,119,I-4m2,Be2OsRu,0.04847,OptB88vdW,0.000
3,JVASP-98225,14,P2_1/c,KBi,-0.44140,OptB88vdW,0.472
4,JVASP-10,164,P-3m1,VSe2,-0.71026,OptB88vdW,0.000

In [113]:
len(data)

55716

In [114]:
data1=data.dropna(axis=0,how='any')

In [115]:
len(data1)

55714

In [116]:
data2=data1.drop(['optb88vdw_bandgap','func','spg_symbol','spg_number','jid'],axis=1)
data2.head()

    formula  formation_energy_peratom
0  TiCuSiAs                  -0.42762
1      DyB6                  -0.41596
2   Be2OsRu                   0.04847
3       KBi                  -0.44140
4      VSe2                  -0.71026

In [117]:
data3=data2.rename(columns={'formation_energy_peratom':'target'})
data3.head()

    formula   target
0  TiCuSiAs -0.42762
1      DyB6 -0.41596
2   Be2OsRu  0.04847
3       KBi -0.44140
4      VSe2 -0.71026

In [118]:
print(f'shape of X:{formula.shape}')
print(f'shape of y:{target.shape}')

shape of X:(55721, 1)
shape of y:(55721, 1)

In [121]:
from sklearn.model_selection import train_test_split

In [40]:
from CBFV import composition

In [131]:
X,y,formulae,skipped=composition.generate_features(data3,elem_prop='oliynyk')

Processing Input Data: 100%|██████████| 55714/55714 [00:01<00:00, 28776.58it/s]

	Featurizing Compositions...

Assigning Features...: 100%|██████████| 55714/55714 [00:03<00:00, 17528.50it/s]

NOTE: Your data contains formula with exotic elements. These were skipped.
	Creating Pandas Objects...

In [132]:
X.head()

#X=data3[['formula']]
#y=data3[['target']]

,avg_Atomic_Number,avg_Atomic_Weight,avg_Period,avg_group,avg_families,avg_Metal,avg_Nonmetal,avg_Metalliod,avg_Mendeleev_Number,avg_l_quantum_number,...,mode_polarizability(A^3),mode_Melting_point_(K),mode_Boiling_Point_(K),mode_Density_(g/mL),mode_specific_heat_(J/g_K)_,mode_heat_of_fusion_(kJ/mol)_,mode_heat_of_vaporization_(kJ/mol)_,mode_thermal_conductivity_(W/(m_K))_,mode_heat_atomization(kJ/mol),mode_Cohesive_energy
0,24.500000,53.608272,3.750000,11.000000,5.000000,0.500000,0.250000,0.250000,67.250000,1.500000,...,4.3,1090.15,890.15,2.33,0.33,13.050,34.76,21.90,302.0,2.960
1,13.714286,32.480857,2.571429,11.571429,5.571429,0.142857,0.000000,0.857143,66.142857,1.285714,...,3.0,2352.15,4275.00,2.34,1.02,50.200,489.70,27.00,573.0,5.810
2,32.000000,77.331090,3.750000,5.000000,3.000000,1.000000,0.000000,0.000000,61.750000,1.000000,...,5.6,1551.15,3243.15,1.85,1.82,7.950,292.40,200.00,324.0,3.320
3,51.000000,124.039335,5.000000,8.000000,3.000000,1.000000,0.000000,0.000000,44.500000,0.500000,...,7.4,336.40,1033.15,0.86,0.12,2.334,79.87,7.87,90.0,0.934
4,30.333333,69.620500,4.000000,12.333333,6.000000,0.333333,0.666667,0.000000,74.666667,1.333333,...,3.8,490.15,958.15,4.79,0.32,6.694,37.70,0.52,227.0,2.460

In [135]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [136]:
len(X_test)

11143

In [138]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import normalize

In [139]:
scaler=StandardScaler()

X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [140]:
X_train_data=normalize(X_train_scaled)
X_test_data=normalize(X_test_scaled)

In [141]:
# Fit a linear regression model
from sklearn.linear_model import LinearRegression

In [143]:
model=LinearRegression()

In [144]:
result=model.fit(X_train,y_train)

In [153]:
r2=model.score(X_train,y_train)
print(r2)

0.8400530210051068

In [154]:
r2_test=model.score(X_test,y_test)
print(r2_test)

0.8369350376253455