# In-class problem
Prior to running this code the CBFV package needs to be installed within the virtual environment


Anaconda Prompt --> conda activate mle5217 -->
pip install CBFV

In [1]:
import pandas as pd
import numpy as np
from CBFV import composition

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv("data/lec05_Thermal_Cond.csv")
data.head()

  Compound  K (W/mK)
0   C12H24    0.1400
1    C3H6O    0.1535
2     C2H2    0.0218
3       Al  255.9400
4    Al2O3    0.0420

In [3]:
data.describe()

         K (W/mK)
count   58.000000
mean    22.464388
std     47.817764
min      0.016000
25%      0.185000
50%      2.550000
75%     18.057500
max    255.940000

In [4]:
data.isna().sum()

Compound    0
K (W/mK)    0
dtype: int64

In [5]:
data=data.rename(columns={"Compound":"formula","K (W/mK)":"target"})
data.head()

  formula    target
0  C12H24    0.1400
1   C3H6O    0.1535
2    C2H2    0.0218
3      Al  255.9400
4   Al2O3    0.0420

In [6]:
X,y,formulae,skipped = composition.generate_features(data,elem_prop='magpie')

Processing Input Data: 100%|█████████████████████████████████████████████████████████| 58/58 [00:00<00:00, 3302.15it/s]

	Featurizing Compositions...

Assigning Features...: 100%|█████████████████████████████████████████████████████████| 58/58 [00:00<00:00, 3552.42it/s]

	Creating Pandas Objects...

In [7]:
type(X)

pandas.core.frame.DataFrame

In [8]:
X.head()

,avg_Number,avg_MendeleevNumber,avg_AtomicWeight,avg_MeltingT,avg_Column,avg_Row,avg_CovalentRadius,avg_Electronegativity,avg_NsValence,avg_NpValence,...,mode_NValence,mode_NsUnfilled,mode_NpUnfilled,mode_NdUnfilled,mode_NfUnfilled,mode_NUnfilled,mode_GSvolume_pa,mode_GSbandgap,mode_GSmagmom,mode_SpaceGroupNumber
0,2.666667,87.0,4.675527,1283.673333,5.333333,1.333333,46.0,2.316667,1.333333,0.666667,...,1.0,1.0,0.0,0.0,0.0,1.0,6.615,7.853,0.0,194.0
1,3.200000,87.0,5.807914,1160.786000,6.400000,1.400000,48.0,2.429000,1.400000,1.000000,...,1.0,1.0,0.0,0.0,0.0,1.0,6.615,7.853,0.0,194.0
2,3.500000,84.5,6.509320,1918.505000,7.500000,1.500000,53.5,2.375000,1.500000,1.000000,...,1.0,0.0,0.0,0.0,0.0,1.0,5.640,4.496,0.0,194.0
3,13.000000,73.0,26.981539,933.470000,13.000000,3.000000,121.0,1.610000,2.000000,1.000000,...,3.0,0.0,5.0,0.0,0.0,5.0,16.480,0.000,0.0,225.0
4,10.000000,81.4,20.392255,406.268000,14.800000,2.400000,88.0,2.708000,2.000000,2.800000,...,6.0,0.0,2.0,0.0,0.0,2.0,9.105,0.000,0.0,12.0

In [9]:
y.head()

0      0.1400
1      0.1535
2      0.0218
3    255.9400
4      0.0420
Name: target, dtype: float64

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=23)

In [11]:
X_train.head()

,avg_Number,avg_MendeleevNumber,avg_AtomicWeight,avg_MeltingT,avg_Column,avg_Row,avg_CovalentRadius,avg_Electronegativity,avg_NsValence,avg_NpValence,...,mode_NValence,mode_NsUnfilled,mode_NpUnfilled,mode_NdUnfilled,mode_NfUnfilled,mode_NUnfilled,mode_GSvolume_pa,mode_GSbandgap,mode_GSmagmom,mode_SpaceGroupNumber
17,4.000000,67.000000,9.012182,1560.00,2.00,2.000000,96.000000,1.5700,2.000000,0.000000,...,2.0,0.0,0.0,0.0,0.0,0.0,7.8900,0.000,0.0,194.0
14,24.666667,65.000000,58.441269,369.00,12.00,3.333333,109.666667,2.9500,2.000000,3.333333,...,7.0,0.0,1.0,0.0,0.0,1.0,9.7075,1.970,0.0,15.0
51,6.666667,60.333333,13.332370,146.56,6.00,2.000000,87.666667,2.1900,1.333333,1.333333,...,1.0,0.0,0.0,0.0,0.0,1.0,6.6150,0.000,0.0,12.0
23,19.250000,84.250000,40.551000,581.45,14.75,3.250000,109.500000,2.8275,2.000000,3.750000,...,7.0,0.0,1.0,0.0,0.0,1.0,24.4975,2.493,0.0,64.0
13,56.000000,9.000000,137.327000,1000.00,2.00,6.000000,215.000000,0.8900,2.000000,0.000000,...,2.0,0.0,0.0,0.0,0.0,0.0,63.5900,0.000,0.0,229.0

In [12]:
list(X_train.columns)

['avg_Number',
 'avg_MendeleevNumber',
 'avg_AtomicWeight',
 'avg_MeltingT',
 'avg_Column',
 'avg_Row',
 'avg_CovalentRadius',
 'avg_Electronegativity',
 'avg_NsValence',
 'avg_NpValence',
 'avg_NdValence',
 'avg_NfValence',
 'avg_NValence',
 'avg_NsUnfilled',
 'avg_NpUnfilled',
 'avg_NdUnfilled',
 'avg_NfUnfilled',
 'avg_NUnfilled',
 'avg_GSvolume_pa',
 'avg_GSbandgap',
 'avg_GSmagmom',
 'avg_SpaceGroupNumber',
 'dev_Number',
 'dev_MendeleevNumber',
 'dev_AtomicWeight',
 'dev_MeltingT',
 'dev_Column',
 'dev_Row',
 'dev_CovalentRadius',
 'dev_Electronegativity',
 'dev_NsValence',
 'dev_NpValence',
 'dev_NdValence',
 'dev_NfValence',
 'dev_NValence',
 'dev_NsUnfilled',
 'dev_NpUnfilled',
 'dev_NdUnfilled',
 'dev_NfUnfilled',
 'dev_NUnfilled',
 'dev_GSvolume_pa',
 'dev_GSbandgap',
 'dev_GSmagmom',
 'dev_SpaceGroupNumber',
 'range_Number',
 'range_MendeleevNumber',
 'range_AtomicWeight',
 'range_MeltingT',
 'range_Column',
 'range_Row',
 'range_CovalentRadius',
 'range_Electronegativity',
 'range_NsValence',
 'range_NpValence',
 'range_NdValence',
 'range_NfValence',
 'range_NValence',
 'range_NsUnfilled',
 'range_NpUnfilled',
 'range_NdUnfilled',
 'range_NfUnfilled',
 'range_NUnfilled',
 'range_GSvolume_pa',
 'range_GSbandgap',
 'range_GSmagmom',
 'range_SpaceGroupNumber',
 'max_Number',
 'max_MendeleevNumber',
 'max_AtomicWeight',
 'max_MeltingT',
 'max_Column',
 'max_Row',
 'max_CovalentRadius',
 'max_Electronegativity',
 'max_NsValence',
 'max_NpValence',
 'max_NdValence',
 'max_NfValence',
 'max_NValence',
 'max_NsUnfilled',
 'max_NpUnfilled',
 'max_NdUnfilled',
 'max_NfUnfilled',
 'max_NUnfilled',
 'max_GSvolume_pa',
 'max_GSbandgap',
 'max_GSmagmom',
 'max_SpaceGroupNumber',
 'min_Number',
 'min_MendeleevNumber',
 'min_AtomicWeight',
 'min_MeltingT',
 'min_Column',
 'min_Row',
 'min_CovalentRadius',
 'min_Electronegativity',
 'min_NsValence',
 'min_NpValence',
 'min_NdValence',
 'min_NfValence',
 'min_NValence',
 'min_NsUnfilled',
 'min_NpUnfilled',
 'min_NdUnfilled',
 'min_NfUnfilled',
 'min_NUnfilled',
 'min_GSvolume_pa',
 'min_GSbandgap',
 'min_GSmagmom',
 'min_SpaceGroupNumber',
 'mode_Number',
 'mode_MendeleevNumber',
 'mode_AtomicWeight',
 'mode_MeltingT',
 'mode_Column',
 'mode_Row',
 'mode_CovalentRadius',
 'mode_Electronegativity',
 'mode_NsValence',
 'mode_NpValence',
 'mode_NdValence',
 'mode_NfValence',
 'mode_NValence',
 'mode_NsUnfilled',
 'mode_NpUnfilled',
 'mode_NdUnfilled',
 'mode_NfUnfilled',
 'mode_NUnfilled',
 'mode_GSvolume_pa',
 'mode_GSbandgap',
 'mode_GSmagmom',
 'mode_SpaceGroupNumber']

In [13]:
print(f'Fraction of training data: {len(X_train)/len(X)}')

Fraction of training data: 0.7931034482758621

In [14]:
linear_model = LinearRegression()
linear_model.fit(X_train,y_train)

LinearRegression()

In [15]:
r2_train=linear_model.score(X_train,y_train)
print(r2_train)

1.0

In [16]:
from sklearn.metrics import r2_score

In [17]:
y_train_pred = linear_model.predict(X_train)
r2_train_value=r2_score(y_train,y_train_pred)
print(r2_train_value)

1.0

In [18]:
y_test_pred =linear_model.predict(X_test)
r2_test_value=r2_score(y_test,y_test_pred)
print(r2_test_value)

-16.437890297991324

**Learning Point!**
Lots of features (descriptors) does not always make good models.


*What's happening here*

We have ~48 training samples and 132 features! There are more unknowns than equations!
e.g. x+y=5 : you can find an infinite number of values for x & y that satisfy this equation. 
That means, you can find a solution that runs through every datapoint exactly!
That's why r2_train=1 --> overfit, but when you look at the test data r2 verlow/negative : terrible!

Lessons!
- if r2=1 or very close to 1 --be very suspicious: check what's wrong!
- if r2_train is high, and r2_test is low --> overfitting to training data
- if r2_test is high and r2_train is significantly low --> that's very strange but could be due to a sampling issue (should try cross-validation instead of simple train-test split)
- if r2_train and test are similar --> very good!
- more features does not always mean a better model - it depends on the data volume / problem complexity and model complexity

In [19]:
#Let's pick out a few features to work with
X_train_selected = X_train[["avg_Number","avg_MendeleevNumber","avg_AtomicWeight","avg_MeltingT","avg_Column","avg_Row"]]	
X_train_selected.head()

X_test_selected = X_test[["avg_Number","avg_MendeleevNumber","avg_AtomicWeight","avg_MeltingT","avg_Column","avg_Row"]]

#Or an easier way
avg_cols = [c for c in X_train.columns if c.startswith('avg_')]  #list comprehension
X_train_selected = X_train[avg_cols]
X_train_selected.head()

avg_test_cols = [c for c in X_test.columns if c.startswith('avg_')]  #list comprehension
X_test_selected = X_test[avg_cols]
X_test_selected.head()

In [20]:
len(X_train_selected)

46

**list comprehension** - The general form is 

*[expression for item in iterable if condition]*

and it builds a new list by iterating over iterable, optionally filtering with the if clause, and evaluating expression for each item that passes.

In [22]:
selected_features_model = LinearRegression()
selected_features_model.fit(X_train_selected,y_train)

LinearRegression()

In [23]:
y_train_selected_pred = selected_features_model.predict(X_train_selected)

r2_train_selected=r2_score(y_train,y_train_selected_pred)
print(r2_train_selected)

0.3401876316092467

In [24]:
y_test_selected_pred = selected_features_model.predict(X_test_selected)
r2_test_selected=r2_score(y_test,y_test_selected_pred)
print(r2_test_selected)

-9.15111898411051


# What are we trying to do?

Predict Thermal conductivity using known features.
But what parameters do K depend on? - in the microscopic regime (not bulk properties) - things like
- atomic/crystal structure (phonons)
- free electron density
- atomic mass
- defects and impurities
- porosity
  are thought to play a role - empirically!

Often we use ML to investigate unknown relationships in physics/chem/mmaterials.
If the relationships are unknown - how do we know which features we need for a good prediction??
**This is a big problem in featurization in classical machine learning**
Which can be overcome/ minimized through Deep learning.

Another important point-
*Defects in materials*: Which plays a major role in many aspects - from property prediction (like this example) to material failure preedictions - but how can we incorporate this in the model??

## Summary of learnings

- We need to investigate how 'meaningful' the task is in terms of science.
  - Does the physics make sense? What are the 'known' descriptors, how accurately can we represent them, what are the limitations, what are the 'unknown' possibilities, can we test their predictability etc.
- Think about the 'meaning' of the problem
- Featurizing the dataset is always preferred to extract chemical information from the formulas.
- Collect data - size of dataset should be much much bigger than the number of features we wish to use (the guideline is at least 10 datapoints per feature - so if you have *n* features, you need *10n* datapoints (minimum) - but this depends on a few other factors  
   - Use dimensionality reduction techniques to find meaningful features / Or use deep learning
- Look out for *perfect fits* a model that predicts the target almost perfectly is too good to be true - there must be something wrong!
   - Try different metrics
   - Try metrics on both train & test splits (they should be similar)
   - Use cross-validation (later)
   - Use models like Ridge regression instead of linear regression (later)

-----

# ☕ Home Work Practice

Download this [dataset](data/lec05-HW_formation_energy.csv) and save it in your environment folder.

The dataset lists formation energies for different materials, try for yourself by following the machine learning process

Inspect data $\rightarrow$ clean data $\rightarrow$ featurization $\rightarrow$ split into train & test $\rightarrow$ build a regression model (you might have to pick suitable features) $\rightarrow$ calculate the metrics 

*You should also try one-hot encoding and see what you get $\rightarrow$ look up matminer package